config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("accounts/", include("allauth.urls")),
    path("users/", include("users.urls", namespace="users")),
    path("remembers/", include("remembers.urls", namespace="remembers")),
    path("martor/", include("martor.urls")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from remembers import views as remember_views
from remembers.views import (
    markdown_uploader,
)

app_name = "core"

urlpatterns = [
    path("", remember_views.HomeView.as_view(), name="home"),
    path("api/uploader/", markdown_uploader, name="markdown_uploader_page"),
]

remembers/urls.py
from django.urls import path
from remembers.views import (
    detail,
    remember_ok,
    remember_ng,
    tagged,
    AllView,
    add,
    edit,
    delete,
    markdown_uploader,
    staged,
)
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = "remembers"

urlpatterns = [
    path("<int:id>/", detail, name="detail"),
    path("ok/", remember_ok, name="ok"),
    path("ng/", remember_ng, name="ng"),
    path("all/", AllView.as_view(), name="all"),
    path("add/", add, name="add"),
    path("edit/<int:id>/", edit, name="edit"),
    path("delete/<int:id>/", delete, name="delete"),
    path("tag/<slug:slug>/", tagged, name="tagged"),
    path("stage/<str:stage>/", staged, name="staged"),
]

remembers/models.py
import json
from datetime import datetime, timedelta
from django.db import models
from core import models as core_models

from taggit.managers import TaggableManager
from martor.models import MartorField


class Stage(core_models.TimeStampedModel):
    pass


class Remember(core_models.TimeStampedModel):
    """Remember Model"""

    user = models.ForeignKey(
        "users.User", related_name="remembers", on_delete=models.CASCADE
    )

    STAGE_1WEEK = "7"
    STAGE_2WEEK = "14"
    STAGE_1MONTH = "30"
    STAGE_2MONTH = "60"
    STAGE_3MONTH = "90"
    STAGE_6MONTH = "180"
    STAGE_1YEAR = "360"

    REMEMBER_STAGE = (
        (STAGE_1WEEK, "1 Week"),
        (STAGE_2WEEK, "2 Week"),
        (STAGE_1MONTH, "1 Month"),
        (STAGE_2MONTH, "2 Month"),
        (STAGE_3MONTH, "3 Month"),
        (STAGE_6MONTH, "6 Month"),
        (STAGE_1YEAR, "1 Year"),
    )

    stage = models.CharField(max_length=7, choices=REMEMBER_STAGE, default=STAGE_1WEEK)

    showing_date = models.DateField(
        "Showing Date", default=datetime.today() + timedelta(days=7)
    )
    remember = MartorField()

    # slug = models.SlugField(unique=True, max_length=100)
    tags = TaggableManager(blank=True)

    # def __str__(self):
    #     time = self.remember["time"]
    #     print(time)
    #     print(self.remember)
    #     print(type(self.remember))
    #     # print(rem)
    #     # print(rem["time"])
    #     # return self.user

    #     # return "test"
    #     return self.user.username + "-" + str(time)


class RememberMeta(models.Model):
    remember = models.ForeignKey(Remember, on_delete=models.CASCADE)
    text = MartorField()

    def __str__(self):
        return self.text

remembers/forms.py
from django import forms
from .models import Remember
from martor.fields import MartorFormField


class RememberForm(forms.ModelForm):
    class Meta:
        model = Remember
        fields = [
            "remember",
            "tags",
        ]

remembers/views.py
import os
import json
import uuid

from datetime import date
from datetime import datetime, timedelta
from django.conf import settings
from django.utils import timezone
from django.http import HttpResponse
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView,
    View,
    UpdateView,
    FormView,
)
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.forms import ModelForm
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile

from martor.utils import LazyEncoder

from .forms import RememberForm

from django.http import JsonResponse
from django.core.files.storage import FileSystemStorage
from django.views.decorators.csrf import requires_csrf_token, csrf_exempt
from django.core.exceptions import BadRequest
from django.contrib.auth.decorators import login_required
from taggit.models import Tag
from .models import Remember


# from users import models


class HomeView(ListView):
    """HomeView Definition"""

    model = Remember

    paginate_by = 5
    paginate_orphans = 2
    # ordering = "created"
    context_object_name = "remembers"
    template_name = "remembers/home.html"
    # print(model)

    def get_queryset(self):
        # print(self.request.user)
        # user_remember = models.Remember.objects.get(user=self.request.user)
        # print(user_remember)
        # print(self.request.user.is_anonymous)
        if self.request.user.is_authenticated:
            # return models.Remember.objects.filter(user=self.request.user)

            return Remember.objects.filter(user=self.request.user).exclude(
                showing_date__gt=date.today()
            )
        else:
            return []

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context["common_tags"] = Remember.tags.most_common()[:4]

        # print(remembers.values("tags"))

        return context


@login_required
def delete(request, id):
    instance = get_object_or_404(Remember, id=id)

    # Remember.objects.filter(id=id).delete()
    instance.delete()
    return redirect("core:home")


@login_required
def edit(request, id):
    instance = get_object_or_404(Remember, id=id)

    form = RememberForm(request.POST or None, instance=instance)
    if form.is_valid():
        form.save()
        return redirect("/remembers/{}/".format(instance.id))
    return render(request, "remembers/edit.html", {"form": form})


@login_required
def detail(request, id):
    # print(request.user)
    # remember = Remember.objects.filter(user=request.user, id=id)
    remember = Remember.objects.filter(user=request.user).get(id=id)
    # print(id)
    print(remember.tags)
    return render(request, "remembers/detail.html", {"remember": remember})


@csrf_exempt
def remember_ok(request):
    user = request.user
    # get remember.

    if request.method == "POST" and request.is_ajax:
        id = request.POST.get("id")
        print(id)
        remember = Remember.objects.get(pk=id)
    # post_id = request.GET.get("data")
    # print("data")
    # print(post_id)

    if user == remember.user:

        for s in Remember.REMEMBER_STAGE:  #
            if remember.stage == s[0]:
                print(remember.stage, s[0], type(s))
                update_idx = Remember.REMEMBER_STAGE.index(s) + 1

                # if already max stage, just let it be
                if update_idx >= len(Remember.REMEMBER_STAGE):
                    break

                remember.stage = Remember.REMEMBER_STAGE[update_idx][0]
                # print(remember.stage)

                break
        # Update showing_date
        for s in Remember.REMEMBER_STAGE:
            if remember.stage == s[0]:
                print(f"updated showing date : {remember.stage}")
                remember.showing_date = datetime.today() + timedelta(
                    days=int(remember.stage)
                )

        remember.save()
        print("remember_ok: ok")
        return HttpResponse("ok :)")

    else:
        # bad request
        return BadRequest("Invalid request.")


@csrf_exempt
def remember_ng(request):
    user = request.user

    if request.method == "POST" and request.is_ajax:
        id = request.POST.get("id")
        print(id)
        remember = Remember.objects.get(pk=id)
    # post_id = request.GET.get("data")
    # print("data")
    # print(post_id)
    # get remember.
    remember = Remember.objects.get(pk=id)

    if user == remember.user:
        remember.stage = Remember.STAGE_1WEEK
        remember.showing_date = datetime.today() + timedelta(days=7)

        remember.save()

        return HttpResponse("ok :)")

    else:
        # bad request
        return BadRequest("Invalid request.")


class AllView(ListView):
    """AllView Definition"""

    model = Remember

    paginate_by = 5
    paginate_orphans = 2
    ordering = "created"
    context_object_name = "remembers"
    template_name = "remembers/all.html"
    # print("AllView")
    # theme = getattr(settings, "MARTOR_THEME", "bootstrap")
    # return render(request, '%s/test_markdownify.html' % theme, context)
    # template_name = "%s/test_markdownify.html" % theme
    # print(template_name)
    # print(model)

    def get_queryset(self):
        # print(self.request.user)
        # user_remember = Remember.objects.get(user=self.request.user)
        # print(user_remember)
        # print(self.request.user.is_anonymous)
        if self.request.user.is_authenticated:
            # return Remember.objects.filter(user=self.request.user)

            # print(Remember.objects.filter(user=self.request.user).order_by("-created"))
            return Remember.objects.filter(user=self.request.user).order_by("-created")
        else:
            return []

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context["common_tags"] = Remember.tags.most_common()[:4]
        return context


def staged(request, stage, all=""):
    print(all)
    # print(stage)
    # stage := "1 Week"
    filter = request.GET.get("filter")

    if request.user.is_authenticated:
        # Fix ME: filter tags=tag has error on django 4.0
        # so, I downgrage django to 3.2

        # print(Remember.REMEMBER_STAGE)

        for s in Remember.REMEMBER_STAGE:  #
            # print(s)
            if stage == s[1]:
                stage_days = s[0]
                break
        remembers = []
        if filter == "all":
            remembers = Remember.objects.filter(user=request.user, stage=stage_days)
        elif filter == "active":
            remembers = Remember.objects.filter(
                user=request.user, stage=stage_days
            ).exclude(showing_date__gt=date.today())

        print(remembers.count())
    else:
        return []

    context = {
        "remembers": remembers,
    }
    return render(request, "remembers/all.html", context)


def tagged(request, slug, all=""):
    print(all)
    filter = request.GET.get("filter")
    tag = get_object_or_404(Tag, slug=slug)
    # print(tag)
    # print(type(slug))
    print(type(tag))
    # Filter posts by tag name
    if request.user.is_authenticated:
        common_tags = Remember.tags.most_common()[:4]
        # print(common_tags)
        # Fix ME: filter tags=tag has error on django 4.0
        # so, I downgrage django to 3.2
        remembers = []
        if filter == "all":
            remembers = Remember.objects.filter(user=request.user, tags=tag)
        elif filter == "active":
            remembers = Remember.objects.filter(user=request.user, tags=tag).exclude(
                showing_date__gt=date.today()
            )

    else:
        return []

    print(remembers)
    context = {
        "tag": tag,
        "common_tags": common_tags,
        "remembers": remembers,
    }

    # FIX ME: need to change template for tagged
    return render(request, "remembers/all.html", context)


@login_required
def add(request):
    user = request.user

    common_tags = Remember.tags.most_common()[:4]
    if request.method == "POST":
        form = RememberForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            remember = form.save(commit=False)
            remember.user = user
            remember.save()
            form.save_m2m()
            return redirect("core:home")
        else:
            # form = RememberForm()  # by this remove : "This field is required."
            print(form.errors.as_data())
    else:  # GET
        form = RememberForm()

    context = {
        "common_tags": common_tags,
        "form": form,
    }
    return render(request, "remembers/add.html", context)


@login_required
def markdown_uploader(request):
    """
    Makdown image upload for locale storage
    and represent as json to markdown editor.
    """
    if request.method == "POST" and request.is_ajax():
        if "markdown-image-upload" in request.FILES:
            image = request.FILES["markdown-image-upload"]
            # print(image)
            image_types = [
                "image/png",
                "image/jpg",
                "image/jpeg",
                "image/pjpeg",
                "image/gif",
            ]
            if image.content_type not in image_types:
                data = json.dumps(
                    {"status": 405, "error": _("Bad image format.")}, cls=LazyEncoder
                )
                return HttpResponse(data, content_type="application/json", status=405)

            if image.size > settings.MAX_IMAGE_UPLOAD_SIZE:

templates/remembers/add.html
{% extends "base.html" %}
{% load static %}
{% block title %}{{ title }} :: {{ block.super }}{% endblock %}
{% block page_title %}
    Add
{% endblock page_title %}

{% block css %}
  <link href="{% static 'plugins/css/ace.min.css' %}" type="text/css" media="all" rel="stylesheet" />
  <link href="{% static 'plugins/css/resizable.min.css' %}" type="text/css" media="all" rel="stylesheet" />
  <link href="{% static 'martor/css/martor.bootstrap.min.css' %}" type="text/css" media="all" rel="stylesheet" />
{% endblock %}

{% block content %}
Write Remember
  <form class="form" method="post">{% csrf_token %}

    <div class="form-group">
      {{ form.remember }}
    </div>
   <!-- https://stackoverflow.com/questions/2902008/django-how-do-i-add-arbitrary-htm
l-attributes-to-input-fields-on-a-form -->
      <div class="form-group">
        <label>Tags</label>
        <input type="text" data-role="tagsinput" class="form-control" name="tags">
      </div>
      <p>Common Tags: 
      {% for mt in common_tags %}
      <a href="#" class="badge badge-success">{{mt}}</a>
      {% endfor %}
      </p>
    <div class="form-group">
      <button class="btn btn-success">
        <i class="save icon"></i> Save Post
      </button>
    </div>
  </form>
{% endblock %}

{% block js %}
  <script type="text/javascript" src="{% static 'plugins/js/ace.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/mode-markdown.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/ext-language_tools.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/theme-github.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/typo.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/spellcheck.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/highlight.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/resizable.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/emojis.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'martor/js/martor.bootstrap.min.js' %}"></script>

  <script>
    $('form [name="remember"]').attr({
      'class': 'form-control',
      'placeholder': 'Remember'
    });
  </script>
{% endblock %}

templates/remembers/all.html
{% extends "base.html" %}
{% load static %}
{% load martortags %}

{% block page_title %}
    All
{% endblock page_title %}

{% block css %}
  <link href="{% static 'plugins/css/ace.min.css' %}" type="text/css" media="all" rel="stylesheet" />
  <link href="{% static 'martor/css/martor.bootstrap.min.css' %}" type="text/css" media="all" rel="stylesheet" />
{% endblock css %}

{% block content %}

    {% if user.is_authenticated %}

    {% if remembers.count != 0 %}
            tags: 
            {% for tag in common_tags %}
            <a href="{% url 'remembers:tagged' tag.slug %}">{{tag}}</a>
            {% endfor %}
        {% endif %}

        <div style="margin: 30px">
            {% for remember in remembers  %}
                {% comment %} <h3>{{remember.stage}}</h3> 
                <h3>{{remember.showing_date}}</h3> {% endcomment %}
                {% for tag in remember.tags.all %}
                    <a href="{% url 'remembers:tagged' tag.slug %}" class="badge badge-info" >{{ tag }}</a>
                {% endfor %}
                
                {{ remember.remember |safe_markdown }}
                <a href="/remembers/edit/{{remember.id}}/">Edit</a>
                <a href="/remembers/delete/{{remember.id}}/">Delete</a>

                <hr style="border: solid #dedede; border-width: 10px 0 0;">

                {% empty %}
                    Perfect! No Remember.
            {% endfor %}
        </div>
    {% else %}
        {% include "introduction.html" %}
    {% endif %}

    
    {% if page_obj.has_next  %}
        Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}

        <a href="?page={{page_obj.next_page_number}}">Next</a>
    {% endif %}

{% endblock content %}


{% block js %}
  <script type="text/javascript" src="{% static 'plugins/js/highlight.min.js' %}"></script>
  <script>
    $('.martor-preview pre').each(function(i, block){
        hljs.highlightBlock(block);
    });
  </script>
{% endblock %}

templates/remembers/detail.html
{% extends 'base.html' %}
{% load static %}
{% load martortags %}

{% block content %}

<a href="/remembers/edit/{{remember.id}}/">Edit</a>
<a href="/remembers/delete/{{remember.id}}/">Delete</a>

{{ remember.remember | safe_markdown}}

{% endblock content %}

templates/remembers/edit.html
{% extends 'base.html' %}
{% block content %}

{% block page_title %}
    Edit
{% endblock page_title %}
{% load static %} {% for message in messages %}

<h1>{{message}}</h1>
{% endfor %}

<form action="" method="POST">
  {% csrf_token %}
  <!--  -->
  {{form.media}}
  <!--  -->
  <div class="field-title">{{ form.as_p }}</div>
  <button>Submit</button>
</form>

<style type="text/css">
    .hidden{
        display:none
    }
</style>
{% endblock content %}

templates/remembers/home.html
{% extends "base.html" %}
{% load static %}
{% load martortags %}

{% block page_title %}
    Home
{% endblock page_title %}

{% block css %}
  <link href="{% static 'plugins/css/ace.min.css' %}" type="text/css" media="all" rel="stylesheet" />
  <link href="{% static 'martor/css/martor.bootstrap.min.css' %}" type="text/css" media="all" rel="stylesheet" />
{% endblock css %}

{% block content %}

    {% if user.is_authenticated %}

    {% if remembers.count != 0 %}
            tags: 
            {% for tag in common_tags %}
            <a href="{% url 'remembers:tagged' tag.slug %}?filter=active">{{tag}}</a>
            {% endfor %}
        {% endif %}

        <div style="margin: 30px">
            {% for remember in remembers  %}
                <div style="box-sizing: border-box;width: 100%;border: solid #5B6DCD 1px;padding: 5px;" class="remember_{{remember.id}}">
                    {% comment %} <h3>{{remember.stage}}</h3> 
                    <h3>{{remember.showing_date}}</h3> {% endcomment %}
                    {% for tag in remember.tags.all %}
                        <a href="{% url 'remembers:tagged' tag.slug %}?filter=active" class="badge badge-info" >{{ tag }}</a>
                    {% endfor %}
                    
                    {{ remember.remember |safe_markdown }}
                    <a href="/remembers/edit/{{remember.id}}/">Edit</a>
                    <a href="/remembers/delete/{{remember.id}}/">Delete</a>

                    <button id="{{remember.id}}" type="button" onclick="remember(this.id)">Remember</button>
                    <button id="{{remember.id}}" type="button" onclick="opps(this.id)">opps</button>
                </div>
                <!-- <hr style="border: solid #dedede; border-width: 10px 0 0;"> -->

                {% empty %}
                    Perfect! No Remember.
            {% endfor %}
        </div>
    {% else %}
        {% include "introduction.html" %}
    {% endif %}

    
    {% if page_obj.has_next  %}
        Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}

        <a href="?page={{page_obj.next_page_number}}">Next</a>
    {% endif %}

{% endblock content %}


{% block js %}
  <script type="text/javascript" src="{% static 'plugins/js/highlight.min.js' %}"></script>
  <script>
    $('.martor-preview pre').each(function(i, block){
        hljs.highlightBlock(block);
    });
  </script>

<script>


    function remember(id) {
        console.log(id)
        $.ajax({
          type: "POST",
          url: "{% url 'remembers:ok' %}",
          //dataType: "json",
          data: {
              "id": id
          },
          success: function(data) {
            //alert("success")
             console.log(data);
             remember_class = `remember_${id}`
             console.log(remember_class)
             //box = document.getElementsByClassName("remember_class");
             $('.' + remember_class).hide()
             //box.style.display="none";
          },
        error: function () {
            alert("error")
        },

      });
    }

    function opps(id) {
        console.log(id)
        $.ajax({
          type: "POST",
          url: "{% url 'remembers:ng' %}",
          //dataType: "json",
          data: {
              "id": id
          },
          success: function(data) {
            //alert("success")
             console.log(data);
             remember_class = `remember_${id}`
             console.log(remember_class)
             //box = document.getElementsByClassName("remember_class");
             $('.' + remember_class).hide()
             //box.style.display="none";
          },
        error: function () {
            alert("error")
        },

      });
    }

</script>
  {% endblock %}

templates/remembers/remember_list.html
{% extends "base.html" %}
{% load static %}
{% load martortags %}

{% block page_title %}
    RememberME
{% endblock page_title %}

{% block css %}
  <link href="{% static 'plugins/css/ace.min.css' %}" type="text/css" media="all" rel="stylesheet" />
  <link href="{% static 'martor/css/martor.bootstrap.min.css' %}" type="text/css" media="all" rel="stylesheet" />
{% endblock css %}

{% block content %}

    {% if user.is_authenticated %}

    {% if remembers.count != 0 %}
            tags: 
            {% for tag in common_tags %}
            <a href="{% url 'remembers:tagged' tag.slug %}">{{tag}}</a>
            {% endfor %}
        {% endif %}

        <div style="margin: 30px">
            {% for remember in remembers  %}
                {% comment %} <h3>{{remember.stage}}</h3> 
                <h3>{{remember.showing_date}}</h3> {% endcomment %}
                {% for tag in remember.tags.all %}
                    <a href="{% url 'remembers:tagged' tag.slug %}" class="badge badge-info" >{{ tag }}</a>
                {% endfor %}
                
                {{ remember.remember |safe_markdown }}
                <a href="/remembers/edit/{{remember.id}}/">Edit</a>
                <a href="/remembers/delete/{{remember.id}}/">Delete</a>

                <hr style="border: solid #dedede; border-width: 10px 0 0;">

                {% empty %}
                    Perfect! No Remember.
            {% endfor %}
        </div>
    {% else %}
        {% include "introduction.html" %}
    {% endif %}

    
    {% if page_obj.has_next  %}
        Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}

        <a href="?page={{page_obj.next_page_number}}">Next</a>
    {% endif %}

{% endblock content %}


{% block js %}
  <script type="text/javascript" src="{% static 'plugins/js/highlight.min.js' %}"></script>
  <script>
    $('.martor-preview pre').each(function(i, block){
        hljs.highlightBlock(block);
    });
  </script>
{% endblock %}