config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("accounts/", include("allauth.urls")),
    path("users/", include("users.urls", namespace="users")),
    path("remembers/", include("remembers.urls", namespace="remembers")),
    path("martor/", include("martor.urls")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from remembers import views as remember_views
from remembers.views import (
    markdown_uploader,
)

app_name = "core"

urlpatterns = [
    path("", remember_views.HomeView.as_view(), name="home"),
    path("api/uploader/", markdown_uploader, name="markdown_uploader_page"),
]

remembers/urls.py
from django.urls import path
from remembers.views import (
    detail,
    remember_ok,
    remember_ng,
    tagged,
    AllView,
    add,
    edit,
    delete,
    markdown_uploader,
    staged,
)
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = "remembers"

urlpatterns = [
    path("<int:id>/", detail, name="detail"),
    path("ok/", remember_ok, name="ok"),
    path("ng/", remember_ng, name="ng"),
    path("all/", AllView.as_view(), name="all"),
    path("add/", add, name="add"),
    path("edit/<int:id>/", edit, name="edit"),
    path("delete/<int:id>/", delete, name="delete"),
    path("tag/<slug:slug>/", tagged, name="tagged"),
    path("stage/<str:stage>/", staged, name="staged"),
]

templates/partials/footer.html
<footer>
    &copy; RememberME
</footer>  

templates/partials/header.html
{% load account %}

<header>
    <a href="/">RememberME</a>
    <ul>
        {% if user.is_active %}
        <li><a href="{{user.get_absolute_url}}">Profile</a></li>
        <li><a href="{% url "remembers:add" %}">Add</a></li>
        <li><a href="{% url "remembers:all" %}">All</a></li>
        <li><a href="{% url "account_logout" %}">Logout</a></li>
        {% else %}
        <li><a href="{% url "account_login" %}">Login</a></li>
        <li><a href="{% url "account_signup" %}">Sign Up</a></li>

        {% endif %}

    </ul>
</header> 