config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("accounts/", include("allauth.urls")),
    path("users/", include("users.urls", namespace="users")),
    path("remembers/", include("remembers.urls", namespace="remembers")),
    path("martor/", include("martor.urls")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from remembers import views as remember_views
from remembers.views import (
    markdown_uploader,
)

app_name = "core"

urlpatterns = [
    path("", remember_views.HomeView.as_view(), name="home"),
    path("api/uploader/", markdown_uploader, name="markdown_uploader_page"),
]

remembers/urls.py
from django.urls import path
from remembers.views import (
    detail,
    remember_ok,
    remember_ng,
    tagged,
    AllView,
    add,
    edit,
    delete,
    markdown_uploader,
    staged,
)
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = "remembers"

urlpatterns = [
    path("<int:id>/", detail, name="detail"),
    path("ok/", remember_ok, name="ok"),
    path("ng/", remember_ng, name="ng"),
    path("all/", AllView.as_view(), name="all"),
    path("add/", add, name="add"),
    path("edit/<int:id>/", edit, name="edit"),
    path("delete/<int:id>/", delete, name="delete"),
    path("tag/<slug:slug>/", tagged, name="tagged"),
    path("stage/<str:stage>/", staged, name="staged"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="logout"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("email_success/", views.email_success, name="email_success"),
]

remembers/models.py
import json
from datetime import datetime, timedelta
from django.db import models
from core import models as core_models

from taggit.managers import TaggableManager
from martor.models import MartorField


class Stage(core_models.TimeStampedModel):
    pass


class Remember(core_models.TimeStampedModel):
    """Remember Model"""

    user = models.ForeignKey(
        "users.User", related_name="remembers", on_delete=models.CASCADE
    )

    STAGE_1WEEK = "7"
    STAGE_2WEEK = "14"
    STAGE_1MONTH = "30"
    STAGE_2MONTH = "60"
    STAGE_3MONTH = "90"
    STAGE_6MONTH = "180"
    STAGE_1YEAR = "360"

    REMEMBER_STAGE = (
        (STAGE_1WEEK, "1 Week"),
        (STAGE_2WEEK, "2 Week"),
        (STAGE_1MONTH, "1 Month"),
        (STAGE_2MONTH, "2 Month"),
        (STAGE_3MONTH, "3 Month"),
        (STAGE_6MONTH, "6 Month"),
        (STAGE_1YEAR, "1 Year"),
    )

    stage = models.CharField(max_length=7, choices=REMEMBER_STAGE, default=STAGE_1WEEK)

    showing_date = models.DateField(
        "Showing Date", default=datetime.today() + timedelta(days=7)
    )
    remember = MartorField()

    # slug = models.SlugField(unique=True, max_length=100)
    tags = TaggableManager(blank=True)

    # def __str__(self):
    #     time = self.remember["time"]
    #     print(time)
    #     print(self.remember)
    #     print(type(self.remember))
    #     # print(rem)
    #     # print(rem["time"])
    #     # return self.user

    #     # return "test"
    #     return self.user.username + "-" + str(time)


class RememberMeta(models.Model):
    remember = models.ForeignKey(Remember, on_delete=models.CASCADE)
    text = MartorField()

    def __str__(self):
        return self.text

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.shortcuts import reverse


class User(AbstractUser):
    def get_absolute_url(self):
        return reverse("users:profile", kwargs={"pk": self.pk})

users/forms.py
from allauth.account.forms import SignupForm


class MyCustomSignupForm(SignupForm):
    def save(self, request):
        print("MyCustomSignupForm")
        # Ensure you call the parent class's save.
        # .save() returns a User object.
        user = super(MyCustomSignupForm, self).save(request)

        # Add your own processing here.

        # You must return the original result.
        return user

users/views.py
from django.views import View
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect, reverse
from django.views.generic import FormView, DetailView, UpdateView
from django.http import HttpResponse
from .models import User
from remembers import models as remember_models


class UserProfileView(DetailView):

    """UserProfileView Definition"""

    model = User
    # context_object_name = "user_obj"
    template_name = "users/profile.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        pk = self.kwargs["pk"]
        tag_set = set()
        stage_list = list()
        stage_remember_number = list()

        user = User.objects.get(pk=pk)

        for s in remember_models.Remember.REMEMBER_STAGE:  #
            # print(s[1])
            stage_list.append(s[1])

            stage_remember_number.append(user.remembers.filter(stage=s[0]).count())
            # print(remember.stage, s[0], type(s))
            # update_idx = Remember.REMEMBER_STAGE.index(s) + 1

        # print(context)
        for remember in user.remembers.all():
            # if not remember.tags.all():
            #    print("None")
            # else:
            # remembers = Remember.objects.filter(user=user, stage=stage_days)
            # print(remembers.count())
            for tag in remember.tags.all():
                # print(tag)
                tag_set.add(tag)
        # context["common_tags"] = User.remembers.tags.most_common()[:4]
        # print(tag_set)
        # print(stage_list)
        # print(remembers.values("tags"))
        context["tags"] = tag_set
        context["stages"] = zip(stage_list, stage_remember_number)
        # context["stages_remember_number"] = stage_remember_number
        return context


class LoginView(View):
    def get(self, request):
        return render(request, "users/login.html")


def log_out(request):
    # messages.info(request, "See you later")
    logout(request)
    return redirect(reverse("core:home"))


def email_success(request):
    res = "Email is verified!"
    # return HttpResponse("<p>%s</p>" % res)
    return redirect(reverse("core:home"))

templates/users/login.html
{% extends "base.html" %}

{% load static %}
{% load socialaccount %}


{% block page_title %}
    Log In
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<a href="{% provider_login_url 'google' method='oauth2' %}">
    Google Login
</a>

<a href="{% provider_login_url 'kakao' method='oauth2' %}">
    Kakao Login
</a>

{% for account in user.socialaccount_set.all %}
<p><img width="50" height="50" src="{{ account.get_avatar_url }}"/></p>

<p>UID: <a href="{{ account.extra_data.link }}">{{ account.uid }}</a></p>

<p>email: {{ account.extra_data.email }}</p>
<p>Name: {{ account.extra_data.name }}</p>
<p>Picture: <img sre="{{ account.extra_data.picture }}" width="100" height="100"></p>
{% endfor %}

{% endblock content %} 

templates/users/profile.html
{% extends "base.html" %}
{% load account %}
{% load static %}
{% load martortags %}


{% block page_title %}
    {% user_display user %}'s Profile
{% endblock page_title %}

{% block content %}
<div>
{% user_display user %}'s Profile
{% if user.socialaccount_set != None %}
<img src="{{ user.socialaccount_set.all.0.get_avatar_url }}" />
{% endif %}
</div>

{% comment %} Display the number of remember in each stage {% endcomment %}

<div>
    <div>
        My tags: 
        {% for tag in tags %}
            <a href="{% url 'remembers:tagged' tag.slug %}?filter=all">{{tag}}</a>
        {% endfor %}
    </div>
    <div>
        stage:

        {% for stage, num in stages %}
            <a href="{% url 'remembers:staged' stage %}?filter=all">{{stage}}({{num}})</a>
        {% endfor %}

        {% for remember in user.remembers.all  %}
            {% comment %} {{ remember.stage }} {% endcomment %}
            {% comment %} {{ remember.get_stage_display }} {% endcomment %}
        {% endfor %}
    </div>


</div>



{% endblock content %} 